name: android_info
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pkg.rahulsharmadev.android_info
        pluginClass: AndroidInfoPlugin
